<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-F70FE3H" failures="0" tests="6" name="com.hrms.testcases.AddEmployeeTest" time="85.657" errors="1" timestamp="2020-09-13T04:08:10 EDT" skipped="0">
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addMultipleEmployees" time="11.001">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hrms.utils.ExcelUtility.getRowsCount(ExcelUtility.java:76)
at com.hrms.utils.ExcelUtility.excelToListMap(ExcelUtility.java:109)
at com.hrms.testcases.AddEmployeeTest.addMultipleEmployees(AddEmployeeTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addMultipleEmployees -->
  <system-out/>
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addEmployeesData" time="14.418"/>
  <system-out/>
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addEmployeesData" time="15.312"/>
  <system-out/>
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addEmployeesData" time="16.136"/>
  <system-out/>
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addEmployeesData" time="14.242"/>
  <system-out/>
  <testcase classname="com.hrms.testcases.AddEmployeeTest" name="addEmployeesData" time="14.548"/>
  <system-out/>
</testsuite> <!-- com.hrms.testcases.AddEmployeeTest -->
